export const Base = {
  GLOBAL_DB_CONTEXT: 'GLOBAL_DB_CONTEXT',
};

export const Services = {
  TRANSACTION: 'TRANSACTION',
};

export const Events = {
  TRANSACTION_INITIATED: 'TRANSACTION_INITIATED',
  TRANSACTION_FINALIZED: 'TRANSACTION_FINALIZED',
};

export const SocketEvents = {
  TRANSACTION_INITIATED: 'TRANSACTION_INITIATED',
  TRANSACTION_FINALIZED: 'TRANSACTION_FINALIZED',
};
